import type { Service, ServiceCategoryInfo } from '@/types/service';
import type { Stylist, Testimonial } from '@/types/user';

export const NAV_LINKS = [
  { label: 'Services', href: '/services' },
  { label: 'Products', href: '/products' },
  { label: 'Hair Fixing', href: '/hair-fixing' },
  { label: 'Blog', href: '/blog' },
  { label: 'About Us', href: '#about' },
  { label: 'Contact', href: '/contact' },
] as const;

export const SERVICE_CATEGORIES: ServiceCategoryInfo[] = [
  { slug: 'haircuts', name: 'Haircuts & Blowouts', description: 'Expert cuts and styling' },
  { slug: 'coloring', name: 'Hair Coloring', description: 'Vibrant, lasting color' },
  { slug: 'spa', name: 'Hair Spa', description: 'Rejuvenating treatments' },
  { slug: 'bridal', name: 'Bridal Styling', description: 'Your perfect day look' },
  { slug: 'treatments', name: 'Treatments', description: 'Advanced hair care' },
  { slug: 'grooming', name: 'Grooming', description: 'Premium grooming services' },
];

export const SERVICES: Service[] = [
  // --- HAIRCUTS & BLOWOUTS ---
  {
    id: '3',
    slug: 'precision-cut',
    name: 'Precision Cut',
    category: 'haircuts',
    description: 'Step into La Belle, where every haircut is a masterpiece. Our stylists are artisans, sculpting each strand to reflect your unique style. From classic cuts to avant-garde designs, we tailor every detail to enhance your natural beauty and leave you feeling confident.',
    shortDescription: 'Every haircut is a masterpiece, tailored to your unique style.',
    price: 1555,
    duration: 45,
    image: '/images/services/precision-cut.jpg',
    featured: true,
  },
  {
    id: '7',
    slug: 'signature-blowout',
    name: 'Signature Blowout',
    category: 'haircuts',
    description: 'Achieve the perfect volume and shine with our Signature Blowout. Whether you want sleek, bouncy, or curly finishes, our experts ensure your hair stays flawless for days.',
    shortDescription: 'Perfect volume and shine for a flawless finish.',
    price: 1100,
    duration: 45,
    image: '/images/gallery/1.png',
    featured: false,
  },
  {
    id: '8',
    slug: 'curtain-bangs',
    name: 'Curtain Bangs & Layers',
    category: 'haircuts',
    description: 'Frame your face elegantly with customized curtain bangs and seamless layers. We texture the ends to create effortless movement and body.',
    shortDescription: 'Customized bangs and seamless layers for effortless movement.',
    price: 1850,
    duration: 60,
    image: '/images/gallery/2.png',
    featured: false,
  },
  {
    id: '9',
    slug: 'french-bob',
    name: 'Classic French Bob',
    category: 'haircuts',
    description: 'A timeless chic haircut tailored exactly to your jawline. This requires extreme precision slicing for acute sharpness and weightlessness at the ends.',
    shortDescription: 'A timeless, jawline-skimming chic bob.',
    price: 2100,
    duration: 60,
    image: '/images/gallery/3.png',
    featured: false,
  },
  {
    id: '27',
    slug: 'textured-shag',
    name: 'Textured Shag Cut',
    category: 'haircuts',
    description: 'A modern, choppy, and layered haircut that gives you an edgy yet sophisticated look. Perfect for natural waves and curly textures.',
    shortDescription: 'A modern, edgy, layered choppy cut.',
    price: 1950,
    duration: 50,
    image: '/images/gallery/6.png',
    featured: false,
  },
  {
    id: '28',
    slug: 'kids-precision',
    name: 'Kids Precision Haircut',
    category: 'haircuts',
    description: 'Gentle, swift, and sharp cuts for the younger ones, administered by highly patient and skilled stylists ensuring complete comfort.',
    shortDescription: 'Gentle and stylish cuts for children.',
    price: 650,
    duration: 30,
    image: '/images/gallery/4.png',
    featured: false,
  },

  // --- COLORING ---
  {
    id: '2',
    slug: 'color-melt',
    name: 'Color Melt',
    category: 'coloring',
    description: 'At La Belle, we transform hair coloring into an art form. Our expert colorists use only the finest pigments to create vibrant, lasting shades that complement your complexion. Experience a personalized color journey, where your hair\'s health and brilliance are our top priorities.',
    shortDescription: 'Vibrant, lasting shades that complement your complexion.',
    price: 5000,
    duration: 90,
    image: '/images/services/color-melt.jpg',
    featured: true,
  },
  {
    id: '5',
    slug: 'balayage',
    name: 'Balayage',
    category: 'coloring',
    description: 'Discover the artistry of balayage at La Belle, where our skilled colorists hand-paint each highlight to create a seamless, sun-kissed effect. We use gentle techniques and nourishing products to ensure your hair remains healthy, vibrant, and effortlessly chic.',
    shortDescription: 'Hand-painted highlights for a seamless, sun-kissed effect.',
    price: 6000,
    duration: 120,
    image: '/images/services/balayage.jpg',
    featured: true,
  },
  {
    id: '11',
    slug: 'babylights',
    name: 'Face-Framing Babylights',
    category: 'coloring',
    description: 'Ultra-fine highlights painted delicately around your hairline to brighten your face beautifully while maintaining an entirely natural, low-maintenance base.',
    shortDescription: 'Delicate hairline highlights for natural brightness.',
    price: 3500,
    duration: 90,
    image: '/images/gallery/4.png',
    featured: false,
  },
  {
    id: '12',
    slug: 'global-color',
    name: 'Global Hair Color',
    category: 'coloring',
    description: 'A rich, uniform color applied from root to tip. Perfect for covering greys or shifting your natural tone using our ammonia-free, nourishing blends.',
    shortDescription: 'Rich, uniform coverage from root to tip.',
    price: 4500,
    duration: 120,
    image: '/images/gallery/5.png',
    featured: false,
  },
  {
    id: '29',
    slug: 'vivid-fashion-colors',
    name: 'Vivid Fashion Colors',
    category: 'coloring',
    description: 'Express yourself with extremely vibrant, custom-mixed fantasy colors including pastels, neon hues, and vivid gem tones. Requires pre-lightening.',
    shortDescription: 'Custom, vibrant fantasy color applications.',
    price: 8500,
    duration: 180,
    image: '/images/gallery/8.png',
    featured: true,
  },
  {
    id: '30',
    slug: 'glossing-toner',
    name: 'Glossing & Toner',
    category: 'coloring',
    description: 'A quick semi-permanent gloss that neutralizes brassiness, adds immense shine, and refreshes existing color beautifully between major visits.',
    shortDescription: 'Refresh color and add immense shine.',
    price: 2500,
    duration: 45,
    image: '/images/gallery/1.png',
    featured: false,
  },

  // --- SPA ---
  {
    id: '14',
    slug: 'deep-conditioning-spa',
    name: 'Deep Conditioning Spa',
    category: 'spa',
    description: 'Intense moisture infusion using keratin and argan oil to rescue dry, damaged, or frizzy hair. Includes a relaxing 20-minute scalp massage.',
    shortDescription: 'Intense moisture infusion with a relaxing scalp massage.',
    price: 2500,
    duration: 60,
    image: '/images/gallery/6.png',
    featured: true,
  },
  {
    id: '15',
    slug: 'aromatherapy-spa',
    name: 'Aromatherapy Hair Spa',
    category: 'spa',
    description: 'Calm your mind and revitalize your hair. Custom-blended essential oils are massaged into the scalp to relieve stress and stimulate hair growth naturally.',
    shortDescription: 'Essential oils to relieve stress and stimulate growth.',
    price: 2800,
    duration: 60,
    image: '/images/gallery/7.png',
    featured: false,
  },
  {
    id: '16',
    slug: 'anti-dandruff-spa',
    name: 'Anti-Dandruff Spa',
    category: 'spa',
    description: 'A purifying treatment utilizing tea tree and salicylic acid formulations to gently exfoliate the scalp, eliminating flakes and soothing irritation.',
    shortDescription: 'Purifying treatment to eliminate flakes and soothe irritation.',
    price: 2600,
    duration: 60,
    image: '/images/gallery/1.png',
    featured: false,
  },
  {
    id: '31',
    slug: 'hot-stone-spa',
    name: 'Hot Stone Scalp SPA',
    category: 'spa',
    description: 'Melt away extreme tension with warm basalt stones gently massaged across the scalp and neck, combined with deeply hydrating mask therapies.',
    shortDescription: 'Warm stone massage for ultimate tension relief.',
    price: 3200,
    duration: 75,
    image: '/images/gallery/7.png',
    featured: false,
  },
  {
    id: '32',
    slug: 'protein-enrichment-spa',
    name: 'Protein Enrichment SPA',
    category: 'spa',
    description: 'Rebuilds hair elasticity and strength instantly through isolated protein infusions targeting chemically weakened and brittle hair strands.',
    shortDescription: 'Rebuilds strength for chemically weakened hair.',
    price: 2900,
    duration: 60,
    image: '/images/gallery/4.png',
    featured: false,
  },

  // --- BRIDAL ---
  {
    id: '6',
    slug: 'bridal-styling',
    name: 'Bridal Styling',
    category: 'bridal',
    description: 'Celebrate your special day with La Belle\'s exquisite bridal styling services. Our talented stylists create breathtaking looks that capture your unique vision, from romantic updos to flowing waves. We ensure every detail is perfect, so you can shine with confidence and grace.',
    shortDescription: 'Breathtaking looks for your special day.',
    price: 15000,
    duration: 180,
    image: '/images/services/bridal-styling.jpg',
    featured: true,
  },
  {
    id: '18',
    slug: 'pre-bridal-pamper',
    name: 'Pre-Bridal Pamper',
    category: 'bridal',
    description: 'A curated bundle combining luxury hair spa, subtle dimension highlights, and skin-prep therapy. Conducted 2 weeks before the big day.',
    shortDescription: 'Curated 2-week prep bundle for brides.',
    price: 12000,
    duration: 240,
    image: '/images/gallery/8.png',
    featured: false,
  },
  {
    id: '19',
    slug: 'bridesmaid-glam',
    name: 'Bridesmaid Glam',
    category: 'bridal',
    description: 'Special group package for elegant updos, bouncy curls, and flawless makeup tailored specifically for the bridal party.',
    shortDescription: 'Elegant hair and makeup for the bridal party.',
    price: 4500,
    duration: 90,
    image: '/images/gallery/3.png',
    featured: false,
  },
  {
    id: '33',
    slug: 'groom-special-pamper',
    name: 'Groom\'s Special Pamper',
    category: 'bridal',
    description: 'A specialized session for the groom featuring classic faded styling, hot towel razor shaping, subtle grey blending, and skin-hydration facials.',
    shortDescription: 'Ultimate grooming session for the big day.',
    price: 7500,
    duration: 120,
    image: '/images/gallery/5.png',
    featured: false,
  },
  {
    id: '34',
    slug: 'bridal-consultation-trial',
    name: 'Pre-Wedding Trial',
    category: 'bridal',
    description: 'One-on-one session to trial different updos, styles, and makeup looks ahead of the event to ensure absolute perfection and peace of mind.',
    shortDescription: 'Style and makeup trials for complete peace of mind.',
    price: 5000,
    duration: 150,
    image: '/images/gallery/2.png',
    featured: false,
  },

  // --- TREATMENTS ---
  {
    id: '1',
    slug: 'scalp-therapy',
    name: 'Scalp Therapy',
    category: 'treatments',
    description: 'At La Belle, we see beauty as a harmony between science and nature. Our treatments are personalized rituals, designed to rejuvenate your hair and spirit. We blend innovative techniques with natural ingredients, ensuring every visit leaves you feeling refreshed and radiant.',
    shortDescription: 'Personalized rituals to rejuvenate your hair and spirit.',
    price: 3500,
    duration: 60,
    image: '/images/services/scalp-therapy.jpg',
    featured: true,
  },
  {
    id: '4',
    slug: 'keratin-smoothing',
    name: 'Keratin Smoothing',
    category: 'treatments',
    description: 'Experience the transformative power of keratin smoothing at La Belle. Our treatments tame frizz, add shine, and reduce styling time, leaving your hair sleek, smooth, and manageable. We customize each treatment to suit your hair type, ensuring optimal results and lasting beauty.',
    shortDescription: 'Tame frizz, add shine, and reduce styling time.',
    price: 7500,
    duration: 120,
    image: '/images/services/keratin-smoothing.jpg',
    featured: true,
  },
  {
    id: '21',
    slug: 'olaplex-treatment',
    name: 'Olaplex Bond Repair',
    category: 'treatments',
    description: 'Rebuild broken disulfide bonds within the hair structure. Essential for highly bleached or chemically compromised hair to restore absolute integrity.',
    shortDescription: 'Rebuild internal bonds for critically damaged hair.',
    price: 4000,
    duration: 45,
    image: '/images/gallery/2.png',
    featured: false,
  },
  {
    id: '22',
    slug: 'botox-treatment',
    name: 'Botox Hair Treatment',
    category: 'treatments',
    description: 'A deep-conditioning "anti-aging" therapy for hair that repairs split ends and deeply hydrates with essential vitamins—without formaldehyde.',
    shortDescription: 'Deep hydration to restructure and plump thin hair.',
    price: 6500,
    duration: 90,
    image: '/images/gallery/4.png',
    featured: false,
  },
  {
    id: '35',
    slug: 'cystine-therapy',
    name: 'Cystine Hair Therapy',
    category: 'treatments',
    description: 'Formulated with naturally occurring amino acids to restore incredibly damaged locks, adding intensive mass and weight to previously thinning hair ends.',
    shortDescription: 'Amino-acid infusion to restore damaged locks.',
    price: 5500,
    duration: 90,
    image: '/images/gallery/7.png',
    featured: false,
  },
  {
    id: '36',
    slug: 'nanoplasty-smoothing',
    name: 'Nanoplasty Smoothing',
    category: 'treatments',
    description: 'An innovative highly effective hair smoothing treatment leveraging nanotechnology to penetrate the hair shaft, providing extreme long-lasting straightness.',
    shortDescription: 'Advanced nanotechnology for long-lasting straightness.',
    price: 9000,
    duration: 150,
    image: '/images/gallery/8.png',
    featured: true,
  },

  // --- GROOMING ---
  {
    id: '23',
    slug: 'classic-fade',
    name: 'Classic Men\'s Fade',
    category: 'grooming',
    description: 'Precision clipper work paired with scissor-over-comb blending. Includes an invigorating hot towel finish and premium styling wax.',
    shortDescription: 'Sharp, tailored fade with a luxurious hot towel finish.',
    price: 850,
    duration: 45,
    image: '/images/gallery/7.png',
    featured: true,
  },
  {
    id: '24',
    slug: 'beard-sculpting',
    name: 'Beard Sculpting',
    category: 'grooming',
    description: 'Line-ups, contouring, and hot lather straight razor shaves. We use premium beard oils to condition and mold coarse facial hair perfectly.',
    shortDescription: 'Contouring and straight razor shaping.',
    price: 650,
    duration: 30,
    image: '/images/gallery/5.png',
    featured: false,
  },
  {
    id: '25',
    slug: 'men-color-camo',
    name: 'Grey Camouflage',
    category: 'grooming',
    description: 'A subtle, 5-minute semi-permanent color application mapping that blends away greys naturally without leaving harsh demarcation lines.',
    shortDescription: 'Subtle blending of greys for a youthful look.',
    price: 1500,
    duration: 30,
    image: '/images/gallery/8.png',
    featured: false,
  },
  {
    id: '37',
    slug: 'hair-fixing-consultation',
    name: 'Hair Fixing Consultation',
    category: 'grooming',
    description: 'A highly confidential, one-on-one session with Mr. Saha SHOW OFF focusing on bespoke hair fixing, patches, and non-surgical restoration mapping.',
    shortDescription: 'Confidential mapping for non-surgical hair restoration.',
    price: 1000,
    duration: 45,
    image: '/images/gallery/1.png',
    featured: true,
  },
  {
    id: '38',
    slug: 'facial-threading',
    name: 'Eyebrow & Facial Threading',
    category: 'grooming',
    description: 'Precision threading to naturally shape the brows and remove unwanted facial hair quickly, with a gentle touch reducing skin irritation.',
    shortDescription: 'Precision threading for eyebrows and facial hair.',
    price: 450,
    duration: 15,
    image: '/images/gallery/6.png',
    featured: false,
  }
];

export const PRICING = {
  haircuts: [
    { name: "LADY'S HAIRCUT (WASH & CUT)", price: '₹ 1,555' },
    { name: 'WASH & BLOWDRY', price: '₹ 3,755' },
    { name: "LADY'S HAIRCUT (WASH & CUT)", price: '₹ 4,555' },
    { name: "GENTLEMEN'S HAIRCUT (WASH & CUT + STYLING)", price: '₹ 5,000' },
    { name: "GENTLEMEN'S HAIRCUT (WASH & CUT + STYLING)", price: '₹ 5,000' },
  ],
  coloring: [
    { name: 'COLOR CONSULTATION', price: 'COMPLIMENTARY' },
    { name: 'DESIGN WORKSHOP', price: '50% OFF' },
    { name: 'BRANDING PACKAGE', price: '$200' },
    { name: 'WEBSITE AUDIT', price: 'FREE' },
    { name: 'MARKETING STRATEGY SESSION', price: '$150' },
  ],
  spa: [
    { name: "NATURE'S SHINE", price: '₹ 7,500' },
    { name: 'HARMONY BLEND', price: '₹ 6,200' },
    { name: "NATURE'S SHINE", price: '₹ 7,500' },
    { name: 'HARMONY BLEND', price: '₹ 6,200' },
  ],
};

export const STATS = [
  { value: '40+', label: 'Years' },
  { value: '06+', label: 'Expert Colorists' },
  { value: '15000+', label: 'Happy Faces' },
  { value: '50+', label: 'Years in Business' },
];

export const STYLISTS: Stylist[] = [
  {
    id: '1',
    name: 'Mr. Saha SHOW OFF',
    role: 'Master Stylist & Founder',
    bio: 'At the age of 52, Saha SHOW OFF stands as a living embodiment of passion, precision, and artistic excellence in hairstyling.',
    image: '/images/gallery/1.png',
    specialties: ['Hair Fixing', 'Celebrity Styling', 'Hair Coloring'],
    experience: 40,
    rating: 5,
    reviewCount: 1200,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Senior Colorist',
    bio: 'Expert colorist specializing in balayage and color corrections with 15 years of experience.',
    image: '/images/gallery/2.png',
    specialties: ['Balayage', 'Color Melt', 'Highlights'],
    experience: 15,
    rating: 4.9,
    reviewCount: 800,
  },
  {
    id: '3',
    name: 'Arjun Kumar',
    role: 'Bridal Specialist',
    bio: 'Renowned bridal hair specialist who has styled over 2000 brides across India.',
    image: '/images/gallery/3.png',
    specialties: ['Bridal Styling', 'Updos', 'Hair Accessories'],
    experience: 12,
    rating: 4.8,
    reviewCount: 600,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Ananya Patel',
    role: 'Regular Client',
    avatar: '/images/gallery/4.png',
    rating: 5,
    text: 'The best salon experience in Bangalore. Mr. Saha truly understands hair like no one else. My hair transformation was incredible!',
  },
  {
    id: '2',
    name: 'Vikram Singh',
    role: 'Business Executive',
    avatar: '/images/gallery/5.png',
    rating: 5,
    text: 'Professional, premium, and precise. Every visit to SHOW OFF feels like a luxury experience. Highly recommend their grooming services.',
  },
  {
    id: '3',
    name: 'Divya Reddy',
    role: 'Bride',
    avatar: '/images/gallery/6.png',
    rating: 5,
    text: 'They made my wedding day hair absolutely perfect. The bridal team understood my vision and exceeded all expectations.',
  },
  {
    id: '4',
    name: 'Rahul Menon',
    role: 'IT Professional',
    avatar: '/images/gallery/7.png',
    rating: 5,
    text: 'I\'ve been coming here for 5 years. The consistency of service quality is remarkable. Best haircut in Mahadevapura, hands down.',
  },
];

export const GALLERY_IMAGES = [
  { id: '1', src: '/images/gallery/1.png', alt: 'Hair styling transformation', category: 'styling' },
  { id: '2', src: '/images/gallery/2.png', alt: 'Color treatment result', category: 'coloring' },
  { id: '3', src: '/images/gallery/3.png', alt: 'Bridal hair styling', category: 'bridal' },
  { id: '4', src: '/images/gallery/4.png', alt: 'Men\'s grooming', category: 'grooming' },
  { id: '5', src: '/images/gallery/5.png', alt: 'Balayage result', category: 'coloring' },
  { id: '6', src: '/images/gallery/6.png', alt: 'Keratin treatment', category: 'treatments' },
  { id: '7', src: '/images/gallery/7.png', alt: 'Hair fixing result', category: 'treatments' },
  { id: '8', src: '/images/gallery/8.png', alt: 'Precision haircut', category: 'styling' },
  { id: '9', src: '/images/gallery/2.png', alt: 'Salon styling', category: 'salon' },
];

export const TIME_SLOTS = [
  '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM',
  '01:00 PM', '01:30 PM', '02:00 PM', '02:30 PM',
  '03:00 PM', '03:30 PM', '04:00 PM', '04:30 PM',
  '05:00 PM', '05:30 PM', '06:00 PM', '06:30 PM',
  '07:00 PM', '07:30 PM', '08:00 PM',
].map((t) => ({ value: t, label: t, available: true }));

export const PRODUCTS = [
  // --- Skin Care & Essential Serums ---
  {
    id: '1',
    name: 'Radiance Glow – Vitamin C Serum',
    category: 'Skin Care & Essential Serums',
    price: '₹ 2,400',
    image: '/images/products/product-1.png',
  },
  {
    id: '2',
    name: 'Ultra Hydrate – Deep Moisturizing Cream',
    category: 'Skin Care & Essential Serums',
    price: '₹ 1,800',
    image: '/images/products/product-2.png',
  },
  {
    id: '3',
    name: 'Luminous Peptide Eye Serum',
    category: 'Skin Care & Essential Serums',
    price: '₹ 3,500',
    image: '/images/products/product-3.png',
  },
  {
    id: '4',
    name: 'Rosewater Hydrating Face Mist',
    category: 'Skin Care & Essential Serums',
    price: '₹ 950',
    image: '/images/products/product-4.png',
  },
  {
    id: '5',
    name: 'Charcoal Detox Clarifying Mask',
    category: 'Skin Care & Essential Serums',
    price: '₹ 1,200',
    image: '/images/products/product-5.png',
  },

  // --- Hair Reborn & Deep Masks ---
  {
    id: '6',
    name: 'SHOW OFF – Keratine Reborn Mask',
    category: 'Hair Reborn & Deep Masks',
    price: '₹ 3,200',
    image: '/images/products/product-6.png',
  },
  {
    id: '7',
    name: 'Argan Oil Extreme Hydration Mask',
    category: 'Hair Reborn & Deep Masks',
    price: '₹ 2,800',
    image: '/images/products/product-1.png',
  },
  {
    id: '8',
    name: 'Bonding Plex Repair System #3',
    category: 'Hair Reborn & Deep Masks',
    price: '₹ 4,500',
    image: '/images/products/product-2.png',
  },
  {
    id: '9',
    name: 'Moroccan Clay Hair Scalp Purifier',
    category: 'Hair Reborn & Deep Masks',
    price: '₹ 1,900',
    image: '/images/products/product-3.png',
  },
  {
    id: '10',
    name: 'Avocado & Honey Nourishing Butter',
    category: 'Hair Reborn & Deep Masks',
    price: '₹ 2,100',
    image: '/images/products/product-4.png',
  },

  // --- Premium Styling & Finishes ---
  {
    id: '11',
    name: 'Flex-Hold Texturizing Sea Salt Spray',
    category: 'Premium Styling & Finishes',
    price: '₹ 1,400',
    image: '/images/products/product-5.png',
  },
  {
    id: '12',
    name: 'Ultimate Shine Argan Hair Serum',
    category: 'Premium Styling & Finishes',
    price: '₹ 1,850',
    image: '/images/products/product-6.png',
  },
  {
    id: '13',
    name: 'Thermal Protection Heat Shield',
    category: 'Premium Styling & Finishes',
    price: '₹ 1,500',
    image: '/images/products/product-1.png',
  },
  {
    id: '14',
    name: 'Matte Finish Clay Pomade',
    category: 'Premium Styling & Finishes',
    price: '₹ 1,100',
    image: '/images/products/product-2.png',
  },
  {
    id: '15',
    name: 'Root Boost Volumizing Mousse',
    category: 'Premium Styling & Finishes',
    price: '₹ 1,350',
    image: '/images/products/product-3.png',
  },

  // --- Grooming & Beard Care ---
  {
    id: '16',
    name: 'Cedarwood Premium Beard Oil',
    category: 'Grooming & Beard Care',
    price: '₹ 1,200',
    image: '/images/products/product-4.png',
  },
  {
    id: '17',
    name: 'Sandalwood Beard Sculpting Balm',
    category: 'Grooming & Beard Care',
    price: '₹ 950',
    image: '/images/products/product-5.png',
  },
  {
    id: '18',
    name: 'Invigorating Peppermint Face Wash',
    category: 'Grooming & Beard Care',
    price: '₹ 800',
    image: '/images/products/product-6.png',
  },
  {
    id: '19',
    name: 'Classic Razor Soothing Aftershave',
    category: 'Grooming & Beard Care',
    price: '₹ 1,450',
    image: '/images/products/product-1.png',
  },
  {
    id: '20',
    name: 'Charcoal Infused Grooming Soap',
    category: 'Grooming & Beard Care',
    price: '₹ 450',
    image: '/images/products/product-2.png',
  },
] as const;

export const EXPERIENCE_SECTIONS = [
  {
    id: '1',
    title: 'HAIR FIXING',
    subtitle: '– The Art Behind Every Transformation',
    quote: 'A Legacy of Style, Precision, and Timeless Elegance',
    description:
      'At the age of 52, Saha SHOW OFF stands as a living embodiment of passion, precision, and artistic excellence in hairstyling. His journey began in the vibrant corridors of celebrity and political circles, where his talent quickly gained recognition among the elite. From a young age, Saha displayed an extraordinary ability to sculpt not just hair, but confidence—turning every style into a statement. Over the decades, his hands have crafted the looks of influential personalities, blending technique with intuition to create styles that reflect individuality. What sets Saha apart is not just his skill, but his deep understanding of people—their personalities,',
    image: '/images/products/experience-1.png',
    imagePosition: 'left' as const,
  },
  {
    id: '2',
    title: 'HAIR FIXING',
    subtitle: '– The Art Behind Every Transformation',
    quote: 'A Legacy of Style, Precision, and Timeless Elegance',
    description:
      'At the age of 52, Saha SHOW OFF stands as a living embodiment of passion, precision, and artistic excellence in hairstyling. His journey began in the vibrant corridors of celebrity and political circles, where his talent quickly gained recognition among the elite. From a young age, Saha displayed an extraordinary ability to sculpt not just hair, but confidence—turning every style into a statement. Over the decades, his hands have crafted the looks of influential personalities, blending technique with intuition to create styles that reflect individuality. What sets Saha apart is not just his skill, but his deep understanding of people—their personalities,',
    image: '/images/products/experience-2.png',
    imagePosition: 'right' as const,
  },
] as const;

export const AWARDS = [
  { year: '2023', title: 'Best Premium Salon in Bangalore', org: 'India Salon Awards' },
  { year: '2021', title: 'Excellence in Hair Fixing', org: 'National Beauty & Wellness Expo' },
  { year: '2019', title: 'Rising Star Master Stylist', org: 'Global Hairdressing Federation' },
];

export const CELEBRITIES = [
  { name: 'Bollywood A-Listers', img: '/images/gallery/1.png' },
  { name: 'Top Regional Icons', img: '/images/gallery/2.png' },
  { name: 'Government Officials', img: '/images/gallery/3.png' },
  { name: 'Business Tycoons', img: '/images/gallery/4.png' },
];
